export const en = {
    'loading': 'Loading...',
    'errors.models.loading': 'Error loading models',
    'errors.models.desc': 'One or more of models cannot be loaded',
    'errors.models.bird': 'Bird model',
    'errors.models.mouse': 'Mouse model',
    'errors.models.ufo': 'UFO model',
    'errors.models.pipe': 'Pipe model',
    'errors.models.background': 'Background model',
    'errors.models.coin': 'Coin model',
    'screens.winner.leader': 'Leader board',
    'screens.winner.title': 'Congratulations you win!',
    'screens.winner.message': 'Now go out and get a life, do not be a geek',
    'screens.winner.message.2': 'Bravo, champ! Now, how about trying out some sunlight?',
    'screens.winner.message.3': 'You won! Feeling proud? Now go do something productive.',
    'screens.winner.message.4': 'Congratulations! Now, can you win in real life?',
    'screens.winner.message.5': 'You\'re the best! At this game... not so much in real life.',
    'screens.winner.message.6': 'You won! Would you like a prize? Sorry, we don\'t have any.',
    'screens.winner.message.7': 'You\'ve won! Now, can you find the exit to your room?',
    'screens.winner.message.8': 'You\'re a winner! In this game... don\'t get too excited.',
    'screens.winner.message.9': 'You\'ve won! Feeling special now?',
    'screens.winner.message.10': 'Congratulations! Now, can you win at something other than a video game?',
    'screens.winner.message.11': 'You\'ve won! Now, can you win in real life?',
    'screens.winner.message.12': 'You won! Would you like a prize? Sorry, we don\'t have any.',
    'screens.winner.message.13': 'You\'re a winner! In this game... don\'t get too excited.',
    'screens.winner.message.14': 'You\'ve won! Feeling special now?',
    'screens.winner.message.15': 'Congratulations! Now, can you win at something other than a video game?',
    'screens.winner.message.16': 'You\'ve won! Now, can you win in real life?',
    'screens.winner.message.17': 'You won! Would you like a prize? Sorry, we don\'t have any.',
    'screens.winner.message.18': 'You\'re a winner! In this game... don\'t get too excited.',
    'screens.winner.message.19': 'You\'ve won! Feeling special now?',
    'screens.winner.message.20': 'Congratulations! Now, can you win at something other than a video game?',
    'screens.winner.message.21': 'You\'ve won! Now, can you win in real life?',

    'screens.loser.leader': 'Leader board',
    'screens.loser.title': 'Congratulations, you lost',
    'screens.loser.message.1': 'Congratulations, you lost. How about trying something easier?',
    'screens.loser.message.2': 'Darn, I think the prize is gone... just like your Ex.',
    'screens.loser.message.3': 'Oh, you lost! Maybe you should try a less challenging game?',
    'screens.loser.message.4': 'You lost. Maybe the sun and fresh air would help you improve?',
    'screens.loser.message.5': 'You lost. Maybe you should try something more productive?',
    'screens.loser.message.6': 'Wow, you lost! Maybe you should stop playing and go out a bit?',
    'screens.loser.message.7': 'You lost, unfortunately... seems like you\'re not as good as you thought.',
    'screens.loser.message.8': 'You almost made it, but you lost. Seriously, don\'t you have anything better to do?',
    'screens.loser.message.9': 'You had one task... and you messed it up. You lost.',
    'screens.loser.message.10': 'Hey hey, look that the prize is gone... just like your dignity.',
    'screens.loser.message.11': 'Bend down and take your prize... oh, wait, you lost.',
    'screens.loser.message.12': 'You could try again... but you lost.',
    'screens.loser.message.13': 'Not to be rude, but I think you\'re not good at this.',
    'screens.loser.message.14': 'Almost there, you were so close... now you just need to learn how to play.',
    'screens.loser.message.15': 'You lost, but don\'t worry, you\'re not the only one.',
    'screens.loser.message.16': 'Careful, it\'s dangerous to lose so much.',
    'screens.loser.message.17': 'You\'re uhhmm, great but maybe not in this game.',
    'screens.loser.message.18': 'Oh great, you still haven\'t won.',
    'screens.loser.message.19': 'What were you expecting, a prize for losing?',
    'screens.loser.message.20': 'Are you playing seriously? You lost.',
    'screens.loser.message.21': 'Wow, you\'re great... at losing.',

    'screens.tap_to_start': 'Tap to start',
    'screens.high_score': 'High score',
    'scores': 'Score',
}