// @ts-ignore
window.flappy_lang = {
    'loading': 'Cargando...',
    'errors.models.loading': 'Error cargando modelos',
    'errors.models.desc': 'Uno o más modelos no pueden ser cargados',
    'errors.models.bird': 'Modelo de pájaro',
    'errors.models.mouse': 'Modelo de ratón',
    'errors.models.ufo': 'Modelo de OVNI',
    'errors.models.pipe': 'Modelo de tubería',
    'errors.models.background': 'Modelo de fondo',
    'errors.models.coin': 'Modelo de moneda',
    'screens.winner.leader': 'Tabla de posiciones',
    'screens.winner.title': '¡Felicidades ganaste!',
    'screens.winner.title_short': '¡Ganaste!',

    'screens.winner.message.1': 'Ahora buscate una vida y sal a la calle, no seas un friki',
    'screens.winner.message.2': '¡Bravo, campeón! Ahora, ¿qué tal si pruebas con la luz del sol?',
    'screens.winner.message.3': '¿Te sientes orgulloso? Ahora ve y haz algo productivo.',
    'screens.winner.message.4': 'pero... ¿puedes ganar en la vida real?',
    'screens.winner.message.5': '¡Eres el mejor! En este juego... en la vida real, no tanto.',
    'screens.winner.message.6': '¿Te gustaría un premio? Lo siento, no tenemos ninguno.',
    'screens.winner.message.7': 'Genial pero... ¿puedes encontrar la salida de tu habitación?',
    'screens.winner.message.8': '¡Eres un ganador! En este juego... no te emociones.',
    'screens.winner.message.9': '¿Te sientes especial ahora?',
    'screens.winner.message.10': 'Ahora, ¿puedes ganar en algo que no sea un videojuego?',
    'screens.winner.message.11': 'Ahora, ¿puedes ganar en la vida real?',
    'screens.winner.message.12': 'Bueno, ya puedes ir a dormir tranquilo... ¿o no?',
    'screens.winner.message.13': '¡Eres un ganador! pero solo en este juego... ¿y la vida que tal?.',
    'screens.winner.message.14': 'Mirenme, le gane a un juego... ¿y ahora qué hago?',
    'screens.winner.message.15': 'Ahora, ¿puedes ganar en algo que no sea un videojuego?',
    'screens.winner.message.16': 'Me asombra que pudieras ganar, espera... ¿por qué estas solo?',
    'screens.winner.message.17': 'Te buscaré un premio... oh, espera, no hay.',
    'screens.winner.message.18': 'Estuviste a punto de perder, a no espera si perdiste tu dignidad.',
    'screens.winner.message.19': 'Eres muy rarito, pero ganaste. ¿Qué sigue, una novia?',
    'screens.winner.message.20': 'Veamos si puedes recoger... este premio imaginario.',
    'screens.winner.message.21': 'Imagina que perdiste... porque no hay premio.',


    'screens.loser.leader': 'Tabla de posiciones',
    'screens.loser.title': 'Felicidades, perdiste',
    'screens.loser.title_short': 'Perdiste',
    'screens.loser.message.1': '¿Qué tal si pruebas con algo más fácil?',
    'screens.loser.message.2': 'Rayos, creo que el premio se fue... igual que tu Ex.',
    'screens.loser.message.3': '¡Oh, rayos! ¿Quizás deberías intentar un juego menos desafiante?',
    'screens.loser.message.4': '¿Quizás el sol y el aire fresco te ayudarían a mejorar?',
    'screens.loser.message.5': '¿Quizás deberías intentar algo más productivo?',
    'screens.loser.message.6': '¡Vaya, enserio! ¿Quizás deberías dejar de jugar y salir un poco?',
    'screens.loser.message.7': 'lamentablemente... parece que no eres tan bueno como pensabas.',
    'screens.loser.message.8': 'Casi lo logras, pero perdiste. enserio, ¿no tienes nada mejor que hacer?',
    'screens.loser.message.9': 'Tenías una sola tarea... y la arruinaste. Perdiste.',
    'screens.loser.message.10': 'Oye oye, mira que el regalo se fue... igual que tu dignidad.',
    'screens.loser.message.11': 'Agachate y toma tu premio... oh, espera, perdiste.',
    'screens.loser.message.12': 'Podrias intentar de nuevo... pero perdiste.',
    'screens.loser.message.13': 'No es por nada, pero creo que no eres bueno en esto.',
    'screens.loser.message.14': 'Casi casi, falto muy poco... ahora solo falta que aprendas a jugar.',
    'screens.loser.message.15': 'pero ey no te preocupes, no eres el único.',
    'screens.loser.message.16': 'Cuidadito, es peligroso perder tanto.',
    'screens.loser.message.17': 'Eres grande, pero tal vez no en este juego.',
    'screens.loser.message.18': 'Oh genial, espera... aún no ganas.',
    'screens.loser.message.19': 'Que esperabas, ¿un premio por perder?',
    'screens.loser.message.20': '¿Estas jugando en serio? no lo parece.',
    'screens.loser.message.21': 'Wow, eres genial... en perder.',
    'screens.loser.message.22': 'Nunca espero nada de ti y siempre logras decepcionarme.',

    'screens.tap_to_start': 'Toca para empezar',
    'screens.high_score': 'Mejor puntaje',
    'score': 'Puntaje',

}
